apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - qdrant.yaml
  - kafka.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - click-consumer.yaml
  - ingress.yaml
